#!/usr/bin/perl
# Prevents the accidental closing of an urxvt window if there is a running process (eg: vim)
# Sends a notification telling you a process is active

sub on_wm_delete_window {
	my ($self, $event) = @_;
	my $CP = `ps --ppid $self->{shell_pid} -o pid= | wc -l`;
	chomp $CP;
	if ( $CP != 0 ) {
		# This will ring the bell:
		#$self->scr_bell;
		#This will send a notification:
		#my $action = `dunstify -h string:x-canonical-private-synchronous:preventclose -i terminal -A 'default,Ignore' -A 'close,Close anyways' 'URxvt' 'A process is currently running'`;
		#if ($action = close) {
		#	return 0;
		#}else{
		#	return 1;
		#}
		system("dunstify -h string:x-canonical-private-synchronous:preventclose -i terminal 'URxvt' 'A process is currently running'");
		return 1;
	} else {
		return 0;
	}
}

sub on_child_start {
	my($self, $pid) = @_;
	$self->{shell_pid} = $pid;
}

